services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DFAU\Ghost\:
    resource: '../Classes/*'

  DFAU\Ghost\Command\ConsumeCommand:
    tags:
      - name: 'console.command'
        command: 'queue:consume'